name: "cedar data_matrix"
description: Cedar data matrix generation from individual quant files
authors:
  - Leandro C. Hermida
notes: |
  * For more information, see https://github.com/COMBINE-lab/pufferfish
