name: subread featurecounts
description: General-purpose program to count reads against genomic features
authors:
  - Leandro C. Hermida
notes: |
  * For more information see, https://subread.sourceforge.net/
