---
wrapper:
  base_url: 'file:wrappers'

tmp_dir: '/home/hermidalc/tmp'

study:
  name: "test"
  samples: "config/samples.tsv"
  units: "config/units.tsv"

gencode:
  protocol: "ftp"
  species: ["human", "mouse"]
  releases: ["41", "M30"]
  builds: ["GRCh38", "GRCm39"]
  regions: "PRI"
  annot:
    fmt: "gtf"
  gene_annot:
    length_col: "Length"
  seqkit:
    replace:
      search_regex: '^(\S+)(?:\s.*)?'

pufferfish:
  binary: './bin/pufferfish'
  ref:
    seqkit:
      seq:
        id_regex: '^(?:\w+\|)?(\S+)'
        line_width: 100
        extra_params: '--upper-case'
  index:
    threads: all
    extra_params: '--keepDuplicates'
  align:
    threads: all

ncbi:
  api_email: 'leandro@leandrohermida.com'
  api_key: '3e48f690c8007a7c8424a3c0ff3d18757808'

  taxonomy:
    acc2taxid:
      url: 'https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/'
      filenames: [
        'dead_nucl.accession2taxid.gz',
        'dead_wgs.accession2taxid.gz',
        'nucl_gb.accession2taxid.gz',
        'nucl_wgs.accession2taxid.gz',
      ]
    taxdump:
      url: 'https://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/'
      zip_filename: 'new_taxdump.zip'
      filenames: [
        'names.dmp',
        'nodes.dmp',
        'rankedlineage.dmp'
      ]
    eukaryote_genera: [
      'Aspergillus',
      'Blastocystis',
      'Candida',
      'Cryptococcus',
      'Cryptosporidium',
      'Cyclospora',
      'Cystoisospora',
      'Entamoeba',
      'Giardia',
      'Leishmania',
      'Malassezia',
      'Neosartorya',
      'Pneumocystis',
      'Saccharomyces',
      'Toxoplasma',
      'Trachipleistophora',
      'Trichinella',
      'Trichomonas',
      'Trypanosoma'
    ]
    low_quality_regex: '(?:C|c)andidat(?:e|us) | _sp(?:_.*|$) | (?:.*_|^)(?:b|B)acterium(?:_.*|) |. *(?:eury|)archaeo(?:n_|te|n$).* |. *(?:endo|)symbiont.* |. *genomosp_.* |. *unidentified.* |. *_bacteria_.* |. *_taxon_.* |. *_et_al_.* |. *_and_.* |. *(?:cyano|proteo|actinobacterium_.*)'

  assembly:
    summary:
      url: 'https://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/'
      filenames: [
      'assembly_summary_genbank.txt',
      'assembly_summary_genbank_historical.txt',
      'assembly_summary_refseq.txt',
      'assembly_summary_refseq_historical.txt',
    ]
    file:
      genome_ext: 'genomic.fna.gz'
      other_exts: [
        'cds_from_genomic.fna.gz',
        # no Pufferfish GFF/GTF support yet
        # 'genomic.gff.gz'
      ]
      download:
        threads: 16
        md5_name: 'md5checksums.txt'
        retries: 5
        force: false
        backend: 'loky'
        verbosity: 1

uniprot:
  proteome:
    ref_metadata_url: 'https://rest.uniprot.org/proteomes/stream?fields=upid%2Corganism_id%2Corganism%2Cgenome_assembly%2Cgenome_representation%2Cprotein_count%2Clineage&format=tsv&query=%2A%20AND%20%28proteome_type%3A1%29'
    other_metadata_url: 'https://rest.uniprot.org/proteomes/stream?fields=upid%2Corganism_id%2Corganism%2Cgenome_assembly%2Cgenome_representation%2Cprotein_count%2Clineage&format=tsv&query=%2A%20AND%20%28proteome_type%3A2%29'
    n_sample: 100
    random_seed: 777
    bacteria_only: false

  kb:
    url: 'https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/'
    filenames: [
      'uniprot_sprot.xml.gz'
    ]

  uniparc:
    url: 'https://ftp.uniprot.org/pub/databases/uniprot/current_release/uniparc/'
    filenames: [
      'uniparc_all.xml.gz'
    ]

seqkit:
  seq:
    threads: 6
  replace:
    threads: 6

fastq:
  data_dir: "data/fastq"
  pairs: ["R1_001", "R2_001"]
  ext: "fq"
  platform: "Illumina"

trimming:
  activate: true
  fastp:
    threads: 8
    extra_params: "--trim_poly_x --detect_adapter_for_pe --correction --low_complexity_filter --overrepresentation_analysis"
