---
wrapper:
  base_url: 'file:wrappers'

tmp_dir: '/home/hermidalc/tmp'

download:
  retries: 5

joblib:
  backend: 'loky'
  verbosity: 1

study:
  name: 'test'
  samples: 'config/samples.tsv'
  units: 'config/units.tsv'

uniprot:
  proteome:
    tax_level: strain
    n_sample: 0
    random_seed: 777
    filter_domains: []
    url:
      ref: 'https://rest.uniprot.org/proteomes/stream?fields=upid%2Corganism_id%2Corganism%2Cgenome_assembly%2Cgenome_representation%2Cprotein_count%2Clineage&format=tsv&query=%2A%20AND%20%28proteome_type%3A1%29'
      other: 'https://rest.uniprot.org/proteomes/stream?fields=upid%2Corganism_id%2Corganism%2Cgenome_assembly%2Cgenome_representation%2Cprotein_count%2Clineage&format=tsv&query=%2A%20AND%20%28proteome_type%3A2%29'
  kb:
    url: 'https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/'
    types: ['sprot', 'trembl']
    parse:
      num_splits: [1, 230]
      split_size: 1e6
    dbxref:
      dbs: [
        'BioCyc',
        'GO',
        'EC',
        'eggNOG',
        'InterPro',
        'KEGG',
        'PANTHER',
        'Pfam',
        'PRINTS',
        'PROSITE',
        'Reactome',
        'TIGRFAMs',
      ]
    pigz:
      threads: 12
    idmap:
      url: 'https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/'
      filename: 'idmapping.dat.gz'
      parse:
        split_size: 1e7
      threads: all

ncbi:
  taxonomy:
    acc2taxid:
      url: 'https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/'
      filenames: [
        'dead_nucl.accession2taxid.gz',
        'dead_wgs.accession2taxid.gz',
        'nucl_gb.accession2taxid.gz',
        'nucl_wgs.accession2taxid.gz',
      ]
    taxdump:
      url: 'https://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/'
      zip_filename: 'new_taxdump.zip'
      filenames: [
        'names.dmp',
        'nodes.dmp',
        'rankedlineage.dmp',
      ]
    eukaryote_genera: [
      'Aspergillus',
      'Blastocystis',
      'Candida',
      'Cryptococcus',
      'Cryptosporidium',
      'Cyclospora',
      'Cystoisospora',
      'Entamoeba',
      'Giardia',
      'Leishmania',
      'Malassezia',
      'Neosartorya',
      'Pneumocystis',
      'Saccharomyces',
      'Toxoplasma',
      'Trachipleistophora',
      'Trichinella',
      'Trichomonas',
      'Trypanosoma',
    ]
    low_quality_pattern: '(?:C|c)andidat(?:e|us) | _sp(?:_.*|$) | (?:.*_|^)(?:b|B)acterium(?:_.*|) |. *(?:eury|)archaeo(?:n_|te|n$).* |. *(?:endo|)symbiont.* |. *genomosp_.* |. *unidentified.* |. *_bacteria_.* |. *_taxon_.* |. *_et_al_.* |. *_and_.* |. *(?:cyano|proteo|actinobacterium_.*)'

  assembly:
    summary:
      url: 'https://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/'
      filenames: [
        'assembly_summary_genbank.txt',
        'assembly_summary_genbank_historical.txt',
        'assembly_summary_refseq.txt',
        'assembly_summary_refseq_historical.txt',
      ]
    file:
      exts: ['genomic.fna.gz', 'cds_from_genomic.fna.gz']
      gff_ext: 'genomic.gff.gz'
      download:
        md5_name: 'md5checksums.txt'
        skip: []
        threads: 16
        file_retries: 5
        file_retry_wait: 5
      seqkit:
        grep:
          pattern: '\[protein_id=.+?\]'
          extra: '--by-name --use-regexp --ignore-case --line-width 80'

ref:
  pigz:
    threads: all
  seqkit:
    seq:
      pattern: '^\w+\|.*?\[protein_id=(.+?)\]'
      extra: '--upper-case --line-width 100'
    rename:
      extra: '--line-width 100'

gencode:
  protocol: 'ftp'
  species: ['human', 'mouse']
  releases: ['42', 'M31']
  builds: ['GRCh38', 'GRCm39']
  regions: 'PRI'
  annot:
    fmt: 'gtf'
  gene_annot:
    length_col: 'Length'
  seqkit:
    replace:
      pattern: '^(\S+)(?:\s.*)?'
      extra: '--line-width 60'

fastq:
  data_dir: 'data/fastq'
  mates: ['R1_001', 'R2_001']
  ext: 'fastq.gz'
  platform: 'Illumina'

trim:
  activate: true
  fastp:
    threads: 8
    extra: '--trim_poly_x --detect_adapter_for_pe --correction --low_complexity_filter --overrepresentation_analysis' # --dedup

pufferfish:
  bin_dir: 'bin/pufferfish/c4db524/linux-x64'
  index:
    threads: all
    extra: '--keepDuplicates'
  align:
    threads: all
    extra: '--coverageScoreRatio 0.5 --genomicReads'
  cedar:
    threads: all
    extra: '--flat --minCnt 2'

cds:
  quant:
    threads: all

seqkit:
  threads: 4

samtools:
  view:
    threads: all

paladin:
  threads: all

diamond:
  threads: all

hisat2:
  threads: all

star:
  index:
    threads: all
  align:
    sort_bam: true
    threads: all
  # regex specific to GTF style
  sj_filter_chr_regex: "^(?!chrM$).+$"  # "chr([1-9][0-9]?|X|Y)"
