---
wrapper:
  base_url: 'file:wrappers'

tmp_dir: '/home/hermidalc/tmp'

pufferfish:
  binary: './external/pufferfish/build/src/pufferfish'
  index:
    threads: 16
  align:
    threads: 16

ncbi:
  api_email: 'leandro@leandrohermida.com'
  api_key: '3e48f690c8007a7c8424a3c0ff3d18757808'

  taxonomy:
    acc2taxid:
      url: 'https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/'
      gz_filenames: [
        'dead_nucl.accession2taxid.gz',
        'dead_wgs.accession2taxid.gz',
        'nucl_gb.accession2taxid.gz',
        'nucl_wgs.accession2taxid.gz',
      ]
    taxdump:
      url: 'https://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/'
      zip_filename: 'new_taxdump.zip'
      filenames: [
        'names.dmp',
        'nodes.dmp',
        'rankedlineage.dmp'
      ]
    eukaryote_genera: [
      'Aspergillus',
      'Blastocystis',
      'Candida',
      'Cryptococcus',
      'Cryptosporidium',
      'Cyclospora',
      'Cystoisospora',
      'Entamoeba',
      'Giardia',
      'Leishmania',
      'Malassezia',
      'Neosartorya',
      'Pneumocystis',
      'Saccharomyces',
      'Toxoplasma',
      'Trachipleistophora',
      'Trichinella',
      'Trichomonas',
      'Trypanosoma'
    ]
    low_quality_regex: '(?:C|c)andidat(?:e|us) | _sp(?:_.*|$) | (?:.*_|^)(?:b|B)acterium(?:_.*|) |. *(?:eury|)archaeo(?:n_|te|n$).* |. *(?:endo|)symbiont.* |. *genomosp_.* |. *unidentified.* |. *_bacteria_.* |. *_taxon_.* |. *_et_al_.* |. *_and_.* |. *(?:cyano|proteo|actinobacterium_.*)'

  assembly:
    summary_url: 'https://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/'
    summary_filenames: [
      'assembly_summary_genbank.txt',
      'assembly_summary_genbank_historical.txt',
      'assembly_summary_refseq.txt',
      'assembly_summary_refseq_historical.txt',
    ]
    file_exts: [
      'cds_from_genomic.fna.gz',
      'genomic.fna.gz',
      # no Pufferfish GFF/GTF support yet
      # 'genomic.gff.gz'
    ]
    download_threads: 16
    download_backend: 'loky'
    download_verbosity: 1
    download_debug: true
    fasta_id_regex: '^(?:\w+\|)?(\S+)'
    fasta_line_width: 80
    seqkit_threads: 8

uniprot:
  proteome:
    ref_metadata_url: 'https://rest.uniprot.org/proteomes/stream?fields=upid%2Corganism_id%2Corganism%2Cgenome_assembly%2Cgenome_representation%2Cprotein_count%2Clineage&format=tsv&query=%2A%20AND%20%28proteome_type%3A1%29'
    other_metadata_url: 'https://rest.uniprot.org/proteomes/stream?fields=upid%2Corganism_id%2Corganism%2Cgenome_assembly%2Cgenome_representation%2Cprotein_count%2Clineage&format=tsv&query=%2A%20AND%20%28proteome_type%3A2%29'
    n_sample: 1000
